name: portfolio-api

services:
  api:
    container_name: portfolio-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    ports:
      - "8002:8002" #同時で立ち上げるとポート番号重複するので8002にする
    volumes:
      - ./src:/app
      - vendor-volume:/app/vendor
      - composer-cache:/tmp/composer/cache
    depends_on:
      - postgres

  postgres:
    container_name: portfolio-api-postgres
    image: postgres:17.4
    environment:
      POSTGRES_HOST: ${POSTGRES_DB_HOST}
      POSTGRES_PORT: ${POSTGRES_DB_PORT}
      POSTGRES_DB: ${POSTGRES_DB_DATABASE}
      POSTGRES_USER: ${POSTGRES_DB_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  composer-cache:
  vendor-volume: